/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// ConfirmOperationRequestActionsInner
    /// </summary>
    [DataContract(Name = "ConfirmOperationRequest_actions_inner")]
    [UnityEngine.Scripting.Preserve]
    public partial class ConfirmOperationRequestActionsInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfirmOperationRequestActionsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConfirmOperationRequestActionsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfirmOperationRequestActionsInner" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="signature">signature (required).</param>
        [UnityEngine.Scripting.Preserve]
        public ConfirmOperationRequestActionsInner(string id = default(string), string signature = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ConfirmOperationRequestActionsInner and cannot be null");
            }
            this.Id = id;
            // to ensure "signature" is required (not null)
            if (signature == null)
            {
                throw new ArgumentNullException("signature is a required property for ConfirmOperationRequestActionsInner and cannot be null");
            }
            this.Signature = signature;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Signature
        /// </summary>
        [DataMember(Name = "signature", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public string Signature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfirmOperationRequestActionsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
