/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// GetOnRampQuoteResponseQuoteInput
    /// </summary>
    [DataContract(Name = "GetOnRampQuoteResponse_quote_input")]
    [UnityEngine.Scripting.Preserve]
    public partial class GetOnRampQuoteResponseQuoteInput
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOnRampQuoteResponseQuoteInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetOnRampQuoteResponseQuoteInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOnRampQuoteResponseQuoteInput" /> class.
        /// </summary>
        /// <param name="paymentCurrency">paymentCurrency (required).</param>
        /// <param name="fiatAmount">fiatAmount (required).</param>
        [UnityEngine.Scripting.Preserve]
        public GetOnRampQuoteResponseQuoteInput(string paymentCurrency = default(string), string fiatAmount = default(string))
        {
            // to ensure "paymentCurrency" is required (not null)
            if (paymentCurrency == null)
            {
                throw new ArgumentNullException("paymentCurrency is a required property for GetOnRampQuoteResponseQuoteInput and cannot be null");
            }
            this.PaymentCurrency = paymentCurrency;
            // to ensure "fiatAmount" is required (not null)
            if (fiatAmount == null)
            {
                throw new ArgumentNullException("fiatAmount is a required property for GetOnRampQuoteResponseQuoteInput and cannot be null");
            }
            this.FiatAmount = fiatAmount;
        }

        /// <summary>
        /// Gets or Sets PaymentCurrency
        /// </summary>
        [DataMember(Name = "paymentCurrency", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public string PaymentCurrency { get; set; }

        /// <summary>
        /// Gets or Sets FiatAmount
        /// </summary>
        [DataMember(Name = "fiatAmount", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public string FiatAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetOnRampQuoteResponseQuoteInput {\n");
            sb.Append("  PaymentCurrency: ").Append(PaymentCurrency).Append("\n");
            sb.Append("  FiatAmount: ").Append(FiatAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
