/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// GetOnRampQuoteResponse
    /// </summary>
    [DataContract(Name = "GetOnRampQuoteResponse")]
    [UnityEngine.Scripting.Preserve]
    public partial class GetOnRampQuoteResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOnRampQuoteResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetOnRampQuoteResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOnRampQuoteResponse" /> class.
        /// </summary>
        /// <param name="quote">quote (required).</param>
        [UnityEngine.Scripting.Preserve]
        public GetOnRampQuoteResponse(GetOnRampQuoteResponseQuote quote = default(GetOnRampQuoteResponseQuote))
        {
            // to ensure "quote" is required (not null)
            if (quote == null)
            {
                throw new ArgumentNullException("quote is a required property for GetOnRampQuoteResponse and cannot be null");
            }
            this.Quote = quote;
        }

        /// <summary>
        /// Gets or Sets Quote
        /// </summary>
        [DataMember(Name = "quote", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public GetOnRampQuoteResponseQuote Quote { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetOnRampQuoteResponse {\n");
            sb.Append("  Quote: ").Append(Quote).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
