/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// GetOnRampQuoteResponseQuote
    /// </summary>
    [DataContract(Name = "GetOnRampQuoteResponse_quote")]
    [UnityEngine.Scripting.Preserve]
    public partial class GetOnRampQuoteResponseQuote
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOnRampQuoteResponseQuote" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetOnRampQuoteResponseQuote() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetOnRampQuoteResponseQuote" /> class.
        /// </summary>
        /// <param name="input">input (required).</param>
        /// <param name="output">output (required).</param>
        [UnityEngine.Scripting.Preserve]
        public GetOnRampQuoteResponseQuote(GetOnRampQuoteResponseQuoteInput input = default(GetOnRampQuoteResponseQuoteInput), GetOnRampQuoteResponseQuoteOutput output = default(GetOnRampQuoteResponseQuoteOutput))
        {
            // to ensure "input" is required (not null)
            if (input == null)
            {
                throw new ArgumentNullException("input is a required property for GetOnRampQuoteResponseQuote and cannot be null");
            }
            this.Input = input;
            // to ensure "output" is required (not null)
            if (output == null)
            {
                throw new ArgumentNullException("output is a required property for GetOnRampQuoteResponseQuote and cannot be null");
            }
            this.Output = output;
        }

        /// <summary>
        /// Gets or Sets Input
        /// </summary>
        [DataMember(Name = "input", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public GetOnRampQuoteResponseQuoteInput Input { get; set; }

        /// <summary>
        /// Gets or Sets Output
        /// </summary>
        [DataMember(Name = "output", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public GetOnRampQuoteResponseQuoteOutput Output { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetOnRampQuoteResponseQuote {\n");
            sb.Append("  Input: ").Append(Input).Append("\n");
            sb.Append("  Output: ").Append(Output).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
