/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// CommonOperationAction
    /// </summary>
    [JsonConverter(typeof(CommonOperationActionJsonConverter))]
    [DataContract(Name = "CommonOperationAction")]
    public partial class CommonOperationAction : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="TransferNFTsAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TransferNFTsAction.</param>
        public CommonOperationAction(TransferNFTsAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="TransferTokenAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TransferTokenAction.</param>
        public CommonOperationAction(TransferTokenAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="MarketplaceCreateOfferAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MarketplaceCreateOfferAction.</param>
        public CommonOperationAction(MarketplaceCreateOfferAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="MarketplaceCancelOfferAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MarketplaceCancelOfferAction.</param>
        public CommonOperationAction(MarketplaceCancelOfferAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="MarketplaceAcceptOfferAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MarketplaceAcceptOfferAction.</param>
        public CommonOperationAction(MarketplaceAcceptOfferAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="MarketplaceListAssetAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MarketplaceListAssetAction.</param>
        public CommonOperationAction(MarketplaceListAssetAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="MarketplaceBuyAssetAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MarketplaceBuyAssetAction.</param>
        public CommonOperationAction(MarketplaceBuyAssetAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="MarketplaceCancelListingAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MarketplaceCancelListingAction.</param>
        public CommonOperationAction(MarketplaceCancelListingAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="SessionRevokeAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SessionRevokeAction.</param>
        public CommonOperationAction(SessionRevokeAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="ExchangeConvertAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ExchangeConvertAction.</param>
        public CommonOperationAction(ExchangeConvertAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="ExchangeWrapAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ExchangeWrapAction.</param>
        public CommonOperationAction(ExchangeWrapAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="ExchangeUnwrapAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ExchangeUnwrapAction.</param>
        public CommonOperationAction(ExchangeUnwrapAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="CustomTransactionAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CustomTransactionAction.</param>
        public CommonOperationAction(CustomTransactionAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationAction" /> class
        /// with the <see cref="SignAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SignAction.</param>
        public CommonOperationAction(SignAction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(CustomTransactionAction) || value is CustomTransactionAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ExchangeConvertAction) || value is ExchangeConvertAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ExchangeUnwrapAction) || value is ExchangeUnwrapAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ExchangeWrapAction) || value is ExchangeWrapAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MarketplaceAcceptOfferAction) || value is MarketplaceAcceptOfferAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MarketplaceBuyAssetAction) || value is MarketplaceBuyAssetAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MarketplaceCancelListingAction) || value is MarketplaceCancelListingAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MarketplaceCancelOfferAction) || value is MarketplaceCancelOfferAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MarketplaceCreateOfferAction) || value is MarketplaceCreateOfferAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MarketplaceListAssetAction) || value is MarketplaceListAssetAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SessionRevokeAction) || value is SessionRevokeAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SignAction) || value is SignAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(TransferNFTsAction) || value is TransferNFTsAction)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(TransferTokenAction) || value is TransferTokenAction)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: CustomTransactionAction, ExchangeConvertAction, ExchangeUnwrapAction, ExchangeWrapAction, MarketplaceAcceptOfferAction, MarketplaceBuyAssetAction, MarketplaceCancelListingAction, MarketplaceCancelOfferAction, MarketplaceCreateOfferAction, MarketplaceListAssetAction, SessionRevokeAction, SignAction, TransferNFTsAction, TransferTokenAction");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `TransferNFTsAction`. If the actual instance is not `TransferNFTsAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TransferNFTsAction</returns>
        public TransferNFTsAction GetTransferNFTsAction()
        {
            return (TransferNFTsAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `TransferTokenAction`. If the actual instance is not `TransferTokenAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TransferTokenAction</returns>
        public TransferTokenAction GetTransferTokenAction()
        {
            return (TransferTokenAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MarketplaceCreateOfferAction`. If the actual instance is not `MarketplaceCreateOfferAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MarketplaceCreateOfferAction</returns>
        public MarketplaceCreateOfferAction GetMarketplaceCreateOfferAction()
        {
            return (MarketplaceCreateOfferAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MarketplaceCancelOfferAction`. If the actual instance is not `MarketplaceCancelOfferAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MarketplaceCancelOfferAction</returns>
        public MarketplaceCancelOfferAction GetMarketplaceCancelOfferAction()
        {
            return (MarketplaceCancelOfferAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MarketplaceAcceptOfferAction`. If the actual instance is not `MarketplaceAcceptOfferAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MarketplaceAcceptOfferAction</returns>
        public MarketplaceAcceptOfferAction GetMarketplaceAcceptOfferAction()
        {
            return (MarketplaceAcceptOfferAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MarketplaceListAssetAction`. If the actual instance is not `MarketplaceListAssetAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MarketplaceListAssetAction</returns>
        public MarketplaceListAssetAction GetMarketplaceListAssetAction()
        {
            return (MarketplaceListAssetAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MarketplaceBuyAssetAction`. If the actual instance is not `MarketplaceBuyAssetAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MarketplaceBuyAssetAction</returns>
        public MarketplaceBuyAssetAction GetMarketplaceBuyAssetAction()
        {
            return (MarketplaceBuyAssetAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MarketplaceCancelListingAction`. If the actual instance is not `MarketplaceCancelListingAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MarketplaceCancelListingAction</returns>
        public MarketplaceCancelListingAction GetMarketplaceCancelListingAction()
        {
            return (MarketplaceCancelListingAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SessionRevokeAction`. If the actual instance is not `SessionRevokeAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SessionRevokeAction</returns>
        public SessionRevokeAction GetSessionRevokeAction()
        {
            return (SessionRevokeAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ExchangeConvertAction`. If the actual instance is not `ExchangeConvertAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ExchangeConvertAction</returns>
        public ExchangeConvertAction GetExchangeConvertAction()
        {
            return (ExchangeConvertAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ExchangeWrapAction`. If the actual instance is not `ExchangeWrapAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ExchangeWrapAction</returns>
        public ExchangeWrapAction GetExchangeWrapAction()
        {
            return (ExchangeWrapAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ExchangeUnwrapAction`. If the actual instance is not `ExchangeUnwrapAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ExchangeUnwrapAction</returns>
        public ExchangeUnwrapAction GetExchangeUnwrapAction()
        {
            return (ExchangeUnwrapAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CustomTransactionAction`. If the actual instance is not `CustomTransactionAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CustomTransactionAction</returns>
        public CustomTransactionAction GetCustomTransactionAction()
        {
            return (CustomTransactionAction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SignAction`. If the actual instance is not `SignAction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SignAction</returns>
        public SignAction GetSignAction()
        {
            return (SignAction)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommonOperationAction {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, CommonOperationAction.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of CommonOperationAction
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of CommonOperationAction</returns>
        public static CommonOperationAction FromJson(string jsonString)
        {
            CommonOperationAction newCommonOperationAction = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newCommonOperationAction;
            }

            try
            {
                var discriminatorObj = JObject.Parse(jsonString)["type"];
                string discriminatorValue =  discriminatorObj == null ?string.Empty :discriminatorObj.ToString();
                switch (discriminatorValue)
                {
                    case "CustomTransaction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<CustomTransactionAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "ExchangeConvert":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeConvertAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "ExchangeUnwrap":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeUnwrapAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "ExchangeWrap":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeWrapAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceAcceptOffer":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceAcceptOfferAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceBuyAsset":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceBuyAssetAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceCancelListing":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCancelListingAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceCancelOffer":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCancelOfferAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceCreateOffer":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCreateOfferAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceListAsset":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceListAssetAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "SessionRevoke":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<SessionRevokeAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "Sign":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<SignAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "TransferNFTs":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<TransferNFTsAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "TransferToken":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<TransferTokenAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "CustomTransactionAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<CustomTransactionAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "ExchangeConvertAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeConvertAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "ExchangeUnwrapAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeUnwrapAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "ExchangeWrapAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeWrapAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceAcceptOfferAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceAcceptOfferAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceBuyAssetAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceBuyAssetAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceCancelListingAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCancelListingAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceCancelOfferAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCancelOfferAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceCreateOfferAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCreateOfferAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "MarketplaceListAssetAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceListAssetAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "SessionRevokeAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<SessionRevokeAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "SignAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<SignAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "TransferNFTsAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<TransferNFTsAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    case "TransferTokenAction":
                        newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<TransferTokenAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                        return newCommonOperationAction;
                    default:
                        System.Diagnostics.Debug.WriteLine(string.Format("Failed to lookup discriminator value `{0}` for CommonOperationAction. Possible values: CustomTransaction ExchangeConvert ExchangeUnwrap ExchangeWrap MarketplaceAcceptOffer MarketplaceBuyAsset MarketplaceCancelListing MarketplaceCancelOffer MarketplaceCreateOffer MarketplaceListAsset SessionRevoke Sign TransferNFTs TransferToken CustomTransactionAction ExchangeConvertAction ExchangeUnwrapAction ExchangeWrapAction MarketplaceAcceptOfferAction MarketplaceBuyAssetAction MarketplaceCancelListingAction MarketplaceCancelOfferAction MarketplaceCreateOfferAction MarketplaceListAssetAction SessionRevokeAction SignAction TransferNFTsAction TransferTokenAction", discriminatorValue));
                        break;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to parse the json data : `{0}` {1}", jsonString, ex.ToString()));
            }

            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CustomTransactionAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<CustomTransactionAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<CustomTransactionAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CustomTransactionAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CustomTransactionAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ExchangeConvertAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeConvertAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeConvertAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ExchangeConvertAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ExchangeConvertAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ExchangeUnwrapAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeUnwrapAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeUnwrapAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ExchangeUnwrapAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ExchangeUnwrapAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ExchangeWrapAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeWrapAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<ExchangeWrapAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ExchangeWrapAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ExchangeWrapAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MarketplaceAcceptOfferAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceAcceptOfferAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceAcceptOfferAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MarketplaceAcceptOfferAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MarketplaceAcceptOfferAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MarketplaceBuyAssetAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceBuyAssetAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceBuyAssetAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MarketplaceBuyAssetAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MarketplaceBuyAssetAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MarketplaceCancelListingAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCancelListingAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCancelListingAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MarketplaceCancelListingAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MarketplaceCancelListingAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MarketplaceCancelOfferAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCancelOfferAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCancelOfferAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MarketplaceCancelOfferAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MarketplaceCancelOfferAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MarketplaceCreateOfferAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCreateOfferAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceCreateOfferAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MarketplaceCreateOfferAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MarketplaceCreateOfferAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MarketplaceListAssetAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceListAssetAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<MarketplaceListAssetAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MarketplaceListAssetAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MarketplaceListAssetAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SessionRevokeAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<SessionRevokeAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<SessionRevokeAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SessionRevokeAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SessionRevokeAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SignAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<SignAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<SignAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SignAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SignAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(TransferNFTsAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<TransferNFTsAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<TransferNFTsAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("TransferNFTsAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TransferNFTsAction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(TransferTokenAction).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<TransferTokenAction>(jsonString, CommonOperationAction.SerializerSettings));
                }
                else
                {
                    newCommonOperationAction = new CommonOperationAction(JsonConvert.DeserializeObject<TransferTokenAction>(jsonString, CommonOperationAction.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("TransferTokenAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TransferTokenAction: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newCommonOperationAction;
        }

    }

    /// <summary>
    /// Custom JSON converter for CommonOperationAction
    /// </summary>
    public class CommonOperationActionJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(CommonOperationAction).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return CommonOperationAction.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return CommonOperationAction.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
