/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// ContextTransferNFTs
    /// </summary>
    [DataContract(Name = "ContextTransferNFTs")]
    [UnityEngine.Scripting.Preserve]
    public partial class ContextTransferNFTs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContextTransferNFTs" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContextTransferNFTs() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContextTransferNFTs" /> class.
        /// </summary>
        /// <param name="assets">assets (required).</param>
        [UnityEngine.Scripting.Preserve]
        public ContextTransferNFTs(List<ContextTransferNFTsAssetsInner> assets = default(List<ContextTransferNFTsAssetsInner>))
        {
            // to ensure "assets" is required (not null)
            if (assets == null)
            {
                throw new ArgumentNullException("assets is a required property for ContextTransferNFTs and cannot be null");
            }
            this.Assets = assets;
        }

        /// <summary>
        /// Gets or Sets Assets
        /// </summary>
        [DataMember(Name = "assets", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public List<ContextTransferNFTsAssetsInner> Assets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContextTransferNFTs {\n");
            sb.Append("  Assets: ").Append(Assets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
