/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// CreateCustomTransactionActionSignature
    /// </summary>
    [JsonConverter(typeof(CreateCustomTransactionActionSignatureJsonConverter))]
    [DataContract(Name = "CreateCustomTransactionAction_signature")]
    public partial class CreateCustomTransactionActionSignature : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCustomTransactionActionSignature" /> class
        /// with the <see cref="CreateSignatureMessage" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CreateSignatureMessage.</param>
        public CreateCustomTransactionActionSignature(CreateSignatureMessage actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCustomTransactionActionSignature" /> class
        /// with the <see cref="CreateSignatureTypedData" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CreateSignatureTypedData.</param>
        public CreateCustomTransactionActionSignature(CreateSignatureTypedData actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(CreateSignatureMessage) || value is CreateSignatureMessage)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(CreateSignatureTypedData) || value is CreateSignatureTypedData)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: CreateSignatureMessage, CreateSignatureTypedData");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `CreateSignatureMessage`. If the actual instance is not `CreateSignatureMessage`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CreateSignatureMessage</returns>
        public CreateSignatureMessage GetCreateSignatureMessage()
        {
            return (CreateSignatureMessage)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CreateSignatureTypedData`. If the actual instance is not `CreateSignatureTypedData`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CreateSignatureTypedData</returns>
        public CreateSignatureTypedData GetCreateSignatureTypedData()
        {
            return (CreateSignatureTypedData)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateCustomTransactionActionSignature {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, CreateCustomTransactionActionSignature.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of CreateCustomTransactionActionSignature
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of CreateCustomTransactionActionSignature</returns>
        public static CreateCustomTransactionActionSignature FromJson(string jsonString)
        {
            CreateCustomTransactionActionSignature newCreateCustomTransactionActionSignature = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newCreateCustomTransactionActionSignature;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CreateSignatureMessage).GetProperty("AdditionalProperties") == null)
                {
                    newCreateCustomTransactionActionSignature = new CreateCustomTransactionActionSignature(JsonConvert.DeserializeObject<CreateSignatureMessage>(jsonString, CreateCustomTransactionActionSignature.SerializerSettings));
                }
                else
                {
                    newCreateCustomTransactionActionSignature = new CreateCustomTransactionActionSignature(JsonConvert.DeserializeObject<CreateSignatureMessage>(jsonString, CreateCustomTransactionActionSignature.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CreateSignatureMessage");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CreateSignatureMessage: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CreateSignatureTypedData).GetProperty("AdditionalProperties") == null)
                {
                    newCreateCustomTransactionActionSignature = new CreateCustomTransactionActionSignature(JsonConvert.DeserializeObject<CreateSignatureTypedData>(jsonString, CreateCustomTransactionActionSignature.SerializerSettings));
                }
                else
                {
                    newCreateCustomTransactionActionSignature = new CreateCustomTransactionActionSignature(JsonConvert.DeserializeObject<CreateSignatureTypedData>(jsonString, CreateCustomTransactionActionSignature.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CreateSignatureTypedData");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CreateSignatureTypedData: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newCreateCustomTransactionActionSignature;
        }

    }

    /// <summary>
    /// Custom JSON converter for CreateCustomTransactionActionSignature
    /// </summary>
    public class CreateCustomTransactionActionSignatureJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(CreateCustomTransactionActionSignature).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return CreateCustomTransactionActionSignature.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return CreateCustomTransactionActionSignature.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
