/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// CreateOperationRequestInputActionsInnerAllOfOneOf1Context
    /// </summary>
    [DataContract(Name = "CreateOperationRequestInput_actions_inner_allOf_oneOf_1_context")]
    [UnityEngine.Scripting.Preserve]
    public partial class CreateOperationRequestInputActionsInnerAllOfOneOf1Context
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOperationRequestInputActionsInnerAllOfOneOf1Context" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        [UnityEngine.Scripting.Preserve]
        protected CreateOperationRequestInputActionsInnerAllOfOneOf1Context() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOperationRequestInputActionsInnerAllOfOneOf1Context" /> class.
        /// </summary>
        /// <param name="amount">amount (required).</param>
        /// <param name="contractAddress">contractAddress (required).</param>
        /// <param name="receiverAddress">receiverAddress (required).</param>
        [UnityEngine.Scripting.Preserve]
        public CreateOperationRequestInputActionsInnerAllOfOneOf1Context(string amount = default(string), string contractAddress = default(string), string receiverAddress = default(string))
        {
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new ArgumentNullException("amount is a required property for CreateOperationRequestInputActionsInnerAllOfOneOf1Context and cannot be null");
            }
            this.Amount = amount;
            // to ensure "contractAddress" is required (not null)
            if (contractAddress == null)
            {
                throw new ArgumentNullException("contractAddress is a required property for CreateOperationRequestInputActionsInnerAllOfOneOf1Context and cannot be null");
            }
            this.ContractAddress = contractAddress;
            // to ensure "receiverAddress" is required (not null)
            if (receiverAddress == null)
            {
                throw new ArgumentNullException("receiverAddress is a required property for CreateOperationRequestInputActionsInnerAllOfOneOf1Context and cannot be null");
            }
            this.ReceiverAddress = receiverAddress;
        }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public string Amount { get; set; }

        /// <summary>
        /// Gets or Sets ContractAddress
        /// </summary>
        [DataMember(Name = "contractAddress", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public string ContractAddress { get; set; }

        /// <summary>
        /// Gets or Sets ReceiverAddress
        /// </summary>
        [DataMember(Name = "receiverAddress", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public string ReceiverAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOperationRequestInputActionsInnerAllOfOneOf1Context {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  ContractAddress: ").Append(ContractAddress).Append("\n");
            sb.Append("  ReceiverAddress: ").Append(ReceiverAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
