/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// CreateOnrampRequestInput
    /// </summary>
    [DataContract(Name = "CreateOnrampRequestInput")]
    [UnityEngine.Scripting.Preserve]
    public partial class CreateOnrampRequestInput
    {
        /// <summary>
        /// Defines Token
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TokenEnum
        {
            /// <summary>
            /// Enum BEAM for value: BEAM
            /// </summary>
            [EnumMember(Value = "BEAM")]
            BEAM = 1
        }


        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        [UnityEngine.Scripting.Preserve]
        public TokenEnum? Token { get; set; }
        /// <summary>
        /// Auth Provider for the user to use. If it&#39;s Any, user will be able to choose his preferred login method. Useful when you want to present social login choice in your UI.
        /// </summary>
        /// <value>Auth Provider for the user to use. If it&#39;s Any, user will be able to choose his preferred login method. Useful when you want to present social login choice in your UI.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AuthProviderEnum
        {
            /// <summary>
            /// Enum Any for value: Any
            /// </summary>
            [EnumMember(Value = "Any")]
            Any = 1,

            /// <summary>
            /// Enum Google for value: Google
            /// </summary>
            [EnumMember(Value = "Google")]
            Google = 2,

            /// <summary>
            /// Enum Discord for value: Discord
            /// </summary>
            [EnumMember(Value = "Discord")]
            Discord = 3,

            /// <summary>
            /// Enum Apple for value: Apple
            /// </summary>
            [EnumMember(Value = "Apple")]
            Apple = 4
        }


        /// <summary>
        /// Auth Provider for the user to use. If it&#39;s Any, user will be able to choose his preferred login method. Useful when you want to present social login choice in your UI.
        /// </summary>
        /// <value>Auth Provider for the user to use. If it&#39;s Any, user will be able to choose his preferred login method. Useful when you want to present social login choice in your UI.</value>
        [DataMember(Name = "authProvider", EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public AuthProviderEnum? AuthProvider { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOnrampRequestInput" /> class.
        /// </summary>
        /// <param name="token">token (default to TokenEnum.BEAM).</param>
        /// <param name="tokenAmount">tokenAmount.</param>
        /// <param name="fiatAmount">fiatAmount.</param>
        /// <param name="paymentCurrency">paymentCurrency (default to &quot;USD&quot;).</param>
        /// <param name="canChangeAmount">canChangeAmount (default to false).</param>
        /// <param name="chainId">chainId (default to 13337).</param>
        /// <param name="authProvider">Auth Provider for the user to use. If it&#39;s Any, user will be able to choose his preferred login method. Useful when you want to present social login choice in your UI. (default to AuthProviderEnum.Any).</param>
        [UnityEngine.Scripting.Preserve]
        public CreateOnrampRequestInput(TokenEnum? token = TokenEnum.BEAM, string tokenAmount = default(string), string fiatAmount = default(string), string paymentCurrency = @"USD", bool canChangeAmount = false, long chainId = 13337, AuthProviderEnum? authProvider = AuthProviderEnum.Any)
        {
            this.Token = token;
            this.TokenAmount = tokenAmount;
            this.FiatAmount = fiatAmount;
            // use default value if no "paymentCurrency" provided
            this.PaymentCurrency = paymentCurrency ?? @"USD";
            this.CanChangeAmount = canChangeAmount;
            this.ChainId = chainId;
            this.AuthProvider = authProvider;
        }

        /// <summary>
        /// Gets or Sets TokenAmount
        /// </summary>
        [DataMember(Name = "tokenAmount", EmitDefaultValue = false)]
        [UnityEngine.Scripting.Preserve]
        public string TokenAmount { get; set; }

        /// <summary>
        /// Gets or Sets FiatAmount
        /// </summary>
        [DataMember(Name = "fiatAmount", EmitDefaultValue = false)]
        [UnityEngine.Scripting.Preserve]
        public string FiatAmount { get; set; }

        /// <summary>
        /// Gets or Sets PaymentCurrency
        /// </summary>
        [DataMember(Name = "paymentCurrency", EmitDefaultValue = false)]
        [UnityEngine.Scripting.Preserve]
        public string PaymentCurrency { get; set; }

        /// <summary>
        /// Gets or Sets CanChangeAmount
        /// </summary>
        [DataMember(Name = "canChangeAmount", EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public bool CanChangeAmount { get; set; }

        /// <summary>
        /// Gets or Sets ChainId
        /// </summary>
        [DataMember(Name = "chainId", EmitDefaultValue = false)]
        [UnityEngine.Scripting.Preserve]
        public long ChainId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOnrampRequestInput {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  TokenAmount: ").Append(TokenAmount).Append("\n");
            sb.Append("  FiatAmount: ").Append(FiatAmount).Append("\n");
            sb.Append("  PaymentCurrency: ").Append(PaymentCurrency).Append("\n");
            sb.Append("  CanChangeAmount: ").Append(CanChangeAmount).Append("\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("  AuthProvider: ").Append(AuthProvider).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
