/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// CreateOperationRequestInputActionsInnerAllOfOneOfTransaction
    /// </summary>
    [DataContract(Name = "CreateOperationRequestInput_actions_inner_allOf_oneOf_transaction")]
    [UnityEngine.Scripting.Preserve]
    public partial class CreateOperationRequestInputActionsInnerAllOfOneOfTransaction
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOperationRequestInputActionsInnerAllOfOneOfTransaction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        [UnityEngine.Scripting.Preserve]
        protected CreateOperationRequestInputActionsInnerAllOfOneOfTransaction() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOperationRequestInputActionsInnerAllOfOneOfTransaction" /> class.
        /// </summary>
        /// <param name="openfortId">openfortId.</param>
        /// <param name="sponsored">sponsored (required).</param>
        [UnityEngine.Scripting.Preserve]
        public CreateOperationRequestInputActionsInnerAllOfOneOfTransaction(string openfortId = default(string), bool sponsored = default(bool))
        {
            this.Sponsored = sponsored;
            this.OpenfortId = openfortId;
        }

        /// <summary>
        /// Gets or Sets OpenfortId
        /// </summary>
        [DataMember(Name = "openfortId", EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public string OpenfortId { get; set; }

        /// <summary>
        /// Gets or Sets Sponsored
        /// </summary>
        [DataMember(Name = "sponsored", IsRequired = true, EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public bool Sponsored { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOperationRequestInputActionsInnerAllOfOneOfTransaction {\n");
            sb.Append("  OpenfortId: ").Append(OpenfortId).Append("\n");
            sb.Append("  Sponsored: ").Append(Sponsored).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
