/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// SignActionSignature
    /// </summary>
    [JsonConverter(typeof(SignActionSignatureJsonConverter))]
    [DataContract(Name = "SignActionSignature")]
    public partial class SignActionSignature : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignActionSignature" /> class
        /// with the <see cref="SignatureRequestMessage" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SignatureRequestMessage.</param>
        public SignActionSignature(SignatureRequestMessage actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SignActionSignature" /> class
        /// with the <see cref="SignatureRequestTypedData" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SignatureRequestTypedData.</param>
        public SignActionSignature(SignatureRequestTypedData actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(SignatureRequestMessage) || value is SignatureRequestMessage)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SignatureRequestTypedData) || value is SignatureRequestTypedData)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: SignatureRequestMessage, SignatureRequestTypedData");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `SignatureRequestMessage`. If the actual instance is not `SignatureRequestMessage`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SignatureRequestMessage</returns>
        public SignatureRequestMessage GetSignatureRequestMessage()
        {
            return (SignatureRequestMessage)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SignatureRequestTypedData`. If the actual instance is not `SignatureRequestTypedData`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SignatureRequestTypedData</returns>
        public SignatureRequestTypedData GetSignatureRequestTypedData()
        {
            return (SignatureRequestTypedData)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SignActionSignature {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, SignActionSignature.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of SignActionSignature
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of SignActionSignature</returns>
        public static SignActionSignature FromJson(string jsonString)
        {
            SignActionSignature newSignActionSignature = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newSignActionSignature;
            }

            try
            {
                var discriminatorObj = JObject.Parse(jsonString)["type"];
                string discriminatorValue =  discriminatorObj == null ?string.Empty :discriminatorObj.ToString();
                switch (discriminatorValue)
                {
                    case "Message":
                        newSignActionSignature = new SignActionSignature(JsonConvert.DeserializeObject<SignatureRequestMessage>(jsonString, SignActionSignature.AdditionalPropertiesSerializerSettings));
                        return newSignActionSignature;
                    case "TypedData":
                        newSignActionSignature = new SignActionSignature(JsonConvert.DeserializeObject<SignatureRequestTypedData>(jsonString, SignActionSignature.AdditionalPropertiesSerializerSettings));
                        return newSignActionSignature;
                    case "SignatureRequestMessage":
                        newSignActionSignature = new SignActionSignature(JsonConvert.DeserializeObject<SignatureRequestMessage>(jsonString, SignActionSignature.AdditionalPropertiesSerializerSettings));
                        return newSignActionSignature;
                    case "SignatureRequestTypedData":
                        newSignActionSignature = new SignActionSignature(JsonConvert.DeserializeObject<SignatureRequestTypedData>(jsonString, SignActionSignature.AdditionalPropertiesSerializerSettings));
                        return newSignActionSignature;
                    default:
                        System.Diagnostics.Debug.WriteLine(string.Format("Failed to lookup discriminator value `{0}` for SignActionSignature. Possible values: Message TypedData SignatureRequestMessage SignatureRequestTypedData", discriminatorValue));
                        break;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to parse the json data : `{0}` {1}", jsonString, ex.ToString()));
            }

            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SignatureRequestMessage).GetProperty("AdditionalProperties") == null)
                {
                    newSignActionSignature = new SignActionSignature(JsonConvert.DeserializeObject<SignatureRequestMessage>(jsonString, SignActionSignature.SerializerSettings));
                }
                else
                {
                    newSignActionSignature = new SignActionSignature(JsonConvert.DeserializeObject<SignatureRequestMessage>(jsonString, SignActionSignature.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SignatureRequestMessage");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SignatureRequestMessage: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SignatureRequestTypedData).GetProperty("AdditionalProperties") == null)
                {
                    newSignActionSignature = new SignActionSignature(JsonConvert.DeserializeObject<SignatureRequestTypedData>(jsonString, SignActionSignature.SerializerSettings));
                }
                else
                {
                    newSignActionSignature = new SignActionSignature(JsonConvert.DeserializeObject<SignatureRequestTypedData>(jsonString, SignActionSignature.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SignatureRequestTypedData");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SignatureRequestTypedData: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newSignActionSignature;
        }

    }

    /// <summary>
    /// Custom JSON converter for SignActionSignature
    /// </summary>
    public class SignActionSignatureJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(SignActionSignature).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return SignActionSignature.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return SignActionSignature.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
